require("lualine").setup()
require("Comment").setup()
require("fidget").setup()
require("lazy.conf.treesitter")
require("lazy.conf.mason-null-ls")
require("lazy.conf.gitsigns")
require("lazy.conf.nvim-tree")
